# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='inactive', max_length=10),
        ),
    ]
