# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-30 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190830_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default=b'inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 6, 36, 22, 993761, tzinfo=utc), verbose_name=b'date published'),
        ),
    ]
