# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-30 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190830_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 6, 38, 12, 888723, tzinfo=utc), verbose_name=b'date published'),
        ),
    ]
