# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-30 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190830_1104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('question', 'choice_text')]),
        ),
    ]
