# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-22 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190830_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(default='inactive', max_length=10),
        ),
    ]
